---
# tasks file for apache
- name: Install httpd Apache
  yum:
    name: httpd
    update_cache: true
    state: present

- name: ensure httpd is enabled and started
  service:
    name: httpd
    state: started
    enabled: true

- name: Populate service facts
  service_facts:
  
- name: Check apache
  debug:
    msg: "Apache service {{ ansible_facts.services['httpd.service'].state }} and {{ ansible_facts.services['httpd.service'].status }}"


- name: Add file index.html
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    #mode: 0644
  notify: restart httpd
    
- name: insert firewalld rule to open ports 443
  firewalld:
    port: "{{ tls_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  
- name: insert firewalld rule to open ports 80
  firewalld:
    port: "{{ no_tls_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
 
- name: check web site from control server   
  uri:
    url: "http://{{ inventory_hostname }}"
    return_content: true
    validate_certs: false
    #connection: local
  register: example_webpage_out
  failed_when: example_webpage_out.status != 200
  
